### ISSUE TITLE
Catalog any update/edit to the dataset page displays square brackets [...] for fields (Bureau code, Program code, Language, Themes, References

### ISSUE THREAD

**Issue by kvuppala** [GSA/datagov-wptheme#548]
1. Catalog any update/edit to the dataset page displays square brackets [...] for fields (Bureau code, Program code, Language, Themes, References
2. In the similar note, when an error occurs on the first save, try to give an existing another dataset URL to generate error, and then fix the URL and save it causes all the extras to go in one big json instead of separate fields. 

Even though the manual edits is not a general practice by admins, it is good to address this issue in case of urgent manual changes that need to be done, or we need to close out the manual Edits completely to avoid the issue. 

Steps to produce:
Navigate to the dataset page (data.json schema 1.1 records) as admin
select the edit button - and save the page with update dataset 
note - the square brackets are displayed even when no changes are made to the dataset- just by saving the page the brackets are displayed

**Comment by kvuppala** [comment]
#1 - is complete, addressed by showing the values properly in UI

#2 - seems like CKAN core issue, which we should plan to address during the CKAN upgrade.

**Comment by hkdctol** [comment]
Seems like this has been addressed.

**Comment by kvuppala** [comment]
Not resolved completely, however we can close this ticket.  This ticket https://github.com/GSA/data.gov/issues/749 will ensure there are no manual edits to datasets except for SysAdmin role.
