### ISSUE TITLE
basemap tiles broken

### ISSUE THREAD

**Issue by tomkralidis** [GSA/datagov-wptheme#738]
As reported in https://github.com/ckan/ckanext-spatial/issues/157, MapQuest tiles now require an AppKey.  This breaks data.gov's (along with numerous other applications) basemaps.  To reproduce, visit http://catalog.data.gov/dataset and see broken basemap tiles in map widget.

**Comment by kvuppala** [comment]
Issue is addressed on http://catalog.data.gov/dataset

**Comment by moqri** [comment]
It seems it's still not working!
http://catalog.data.gov/dataset/demographic-statistics-by-zip-code-acfc9/resource/e43f1938-3c4a-4501-9aaf-46891bb21553
